name = "PackageRepository"
uuid = "66e69e57-c158-407d-b02d-e105ef18005a"
repo = "https://github.com/mipals/PackageRepository.git"
description = "My private registry"

[packages]
ebf54fa4-afc0-484a-8ee1-77aaf84d33dc = { name = "IntegralEquations", path = "I/IntegralEquations" }
